### ISSUE TITLE
Could not find a version that satisfies the requirement aquiladb

### ISSUE THREAD

**Issue by freakeinstein** [a-mma/AquilaDB-Python#1]
When I try to install AquilaDB via pip install `pip install aquiladb` it is giving me this error:
```
Could not find a version that satisfies the requirement aquiladb (from versions: )
No matching distribution found for aquiladb
```

**Comment by freakeinstein** [comment]
![image](https://user-images.githubusercontent.com/19545678/61170017-3a5c4300-a581-11e9-958a-313445de096f.png)

**Comment by Haroldgomez777** [comment]
works on python 3.
